"""ingestion run source checksum

Revision ID: 191a933a9a77
Revises: adc4e987a7c2
Create Date: 2026-10-08 10:28:19.633100
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '191a933a9a77'
down_revision: str | None = 'adc4e987a7c2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion_runs', sa.Column('source_checksum', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestion_runs', 'source_checksum')
    # ### end Alembic commands ###
