"""promoter normalized key

Revision ID: a78efbc0aafa
Revises: bb53889ace17
Create Date: 2026-10-06 16:48:22.860817
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'a78efbc0aafa'
down_revision: str | None = 'bb53889ace17'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promoters', sa.Column('normalized_key', sa.String(length=512), nullable=False))
    op.drop_constraint(op.f('promoters_canonical_name_key'), 'promoters', type_='unique')
    op.create_index(op.f('ix_promoters_normalized_key'), 'promoters', ['normalized_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promoters_normalized_key'), table_name='promoters')
    op.create_unique_constraint(op.f('promoters_canonical_name_key'), 'promoters', ['canonical_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('promoters', 'normalized_key')
    # ### end Alembic commands ###
