"""history indexes

Revision ID: adc4e987a7c2
Revises: a78efbc0aafa
Create Date: 2026-10-08 10:26:46.487811
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'adc4e987a7c2'
down_revision: str | None = 'a78efbc0aafa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_project_change_events_detected_at'), 'project_change_events', ['detected_at'], unique=False)
    op.create_index(op.f('ix_project_change_events_field_name'), 'project_change_events', ['field_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_change_events_field_name'), table_name='project_change_events')
    op.drop_index(op.f('ix_project_change_events_detected_at'), table_name='project_change_events')
    # ### end Alembic commands ###
