"""initial schema

Revision ID: bb53889ace17
Revises: 
Create Date: 2026-10-06 15:42:32.594504
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'bb53889ace17'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('collection_method', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('parser_version', sa.String(length=32), nullable=True),
    sa.Column('records_found', sa.Integer(), nullable=False),
    sa.Column('records_inserted', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_unchanged', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('errors_count', sa.Integer(), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promoters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=512), nullable=False),
    sa.Column('match_method', sa.String(length=64), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name')
    )
    op.create_table('baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('baseline_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('parser_version', sa.String(length=32), nullable=True),
    sa.Column('source_checksum', sa.String(length=128), nullable=True),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rera_registration_number', sa.String(length=255), nullable=False),
    sa.Column('project_name', sa.Text(), nullable=True),
    sa.Column('promoter_name_raw', sa.Text(), nullable=True),
    sa.Column('promoter_id', sa.Integer(), nullable=True),
    sa.Column('project_type', sa.String(length=128), nullable=True),
    sa.Column('project_status', sa.String(length=128), nullable=True),
    sa.Column('project_start_date', sa.Date(), nullable=True),
    sa.Column('declared_completion_date', sa.Date(), nullable=True),
    sa.Column('certificate_number', sa.String(length=255), nullable=True),
    sa.Column('certificate_date', sa.Date(), nullable=True),
    sa.Column('last_modified_date', sa.Date(), nullable=True),
    sa.Column('total_units', sa.Integer(), nullable=True),
    sa.Column('sold_units', sa.Integer(), nullable=True),
    sa.Column('district', sa.String(length=128), nullable=True),
    sa.Column('taluk', sa.String(length=128), nullable=True),
    sa.Column('village', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('not_seen_in_latest_run', sa.Boolean(), nullable=False),
    sa.Column('consecutive_misses', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['promoter_id'], ['promoters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rera_registration_number', name='uq_projects_rera_registration_number')
    )
    op.create_index(op.f('ix_projects_rera_registration_number'), 'projects', ['rera_registration_number'], unique=False)
    op.create_table('data_quality_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('field_name', sa.String(length=128), nullable=True),
    sa.Column('issue_type', sa.String(length=128), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_quality_issues_ingestion_run_id'), 'data_quality_issues', ['ingestion_run_id'], unique=False)
    op.create_index(op.f('ix_data_quality_issues_project_id'), 'data_quality_issues', ['project_id'], unique=False)
    op.create_table('project_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rera_registration_number', sa.String(length=255), nullable=True),
    sa.Column('project_name', sa.Text(), nullable=True),
    sa.Column('promoter_name_raw', sa.Text(), nullable=True),
    sa.Column('project_type', sa.String(length=128), nullable=True),
    sa.Column('project_status', sa.String(length=128), nullable=True),
    sa.Column('project_start_date', sa.Date(), nullable=True),
    sa.Column('declared_completion_date', sa.Date(), nullable=True),
    sa.Column('certificate_number', sa.String(length=255), nullable=True),
    sa.Column('certificate_date', sa.Date(), nullable=True),
    sa.Column('last_modified_date', sa.Date(), nullable=True),
    sa.Column('total_units', sa.Integer(), nullable=True),
    sa.Column('sold_units', sa.Integer(), nullable=True),
    sa.Column('district', sa.String(length=128), nullable=True),
    sa.Column('taluk', sa.String(length=128), nullable=True),
    sa.Column('village', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_record', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_snapshots_project_id'), 'project_snapshots', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_snapshots_source_hash'), 'project_snapshots', ['source_hash'], unique=False)
    op.create_table('project_change_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('field_name', sa.String(length=128), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('source_last_modified_date', sa.Date(), nullable=True),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['project_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_change_events_project_id'), 'project_change_events', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_change_events_project_id'), table_name='project_change_events')
    op.drop_table('project_change_events')
    op.drop_index(op.f('ix_project_snapshots_source_hash'), table_name='project_snapshots')
    op.drop_index(op.f('ix_project_snapshots_project_id'), table_name='project_snapshots')
    op.drop_table('project_snapshots')
    op.drop_index(op.f('ix_data_quality_issues_project_id'), table_name='data_quality_issues')
    op.drop_index(op.f('ix_data_quality_issues_ingestion_run_id'), table_name='data_quality_issues')
    op.drop_table('data_quality_issues')
    op.drop_index(op.f('ix_projects_rera_registration_number'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('baselines')
    op.drop_table('promoters')
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
