"""Analytics package: read-only queries and promoter identity.

Nothing here writes to the source data tables; the only mutation is the
explicit promoter canonicalisation build (``promoters.build_promoters``).
"""

from rera.analytics.promoters import (
    PromoterBuildResult,
    build_promoters,
    canonical_key,
)
from rera.analytics.queries import (
    baseline,
    builder_concentration,
    builder_detail,
    by_builder,
    by_district,
    by_taluk,
    data_quality_summary,
    district_detail,
    filter_options,
    get_project,
    history_summary,
    overdue_projects,
    overdue_summary,
    overview,
    project_changes,
    project_history,
    project_mix_by_district,
    recent_changes,
    recent_projects,
    registration_trend,
    runs,
    search_projects,
    supply_pipeline,
    taluk_detail,
    taluks_for_district,
    timeline,
    unsold_inventory,
    village_detail,
    villages_for,
)

__all__ = [
    "PromoterBuildResult",
    "build_promoters",
    "canonical_key",
    "baseline",
    "builder_concentration",
    "builder_detail",
    "by_builder",
    "by_district",
    "by_taluk",
    "data_quality_summary",
    "district_detail",
    "filter_options",
    "get_project",
    "history_summary",
    "overview",
    "overdue_projects",
    "overdue_summary",
    "project_changes",
    "project_history",
    "project_mix_by_district",
    "recent_changes",
    "recent_projects",
    "registration_trend",
    "runs",
    "search_projects",
    "supply_pipeline",
    "taluk_detail",
    "taluks_for_district",
    "timeline",
    "unsold_inventory",
    "village_detail",
    "villages_for",
]
